### Get all tools
GET http://localhost:3000/tools

### Get one tool by id
GET http://localhost:3000/tools/6a12422733106937be745647

### Create new tool
POST http://localhost:3000/tools
Content-Type: application/json

{
  "toolName": "Cordless Drill",
  "brand": "DeWalt",
  "category": "Power Tool",
  "condition": "Good",
  "purchaseYear": 2023,
  "available": true,
  "notes": "Used for garage projects"
}